import { useEffect, useState, type FormEvent } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { useTranslation } from "react-i18next";

import { useAuth } from "@/auth/AuthProvider";
import { NexButton } from "@/components/NexButton";
import { NexInput } from "@/components/NexInput";
import { NexSelect } from "@/components/NexSelect";
import { NexText } from "@/components/NexText";
import { deleteUser, getUser, updateUser } from "@/requests/users";
import { listRoles, setRoleUser } from "@/requests/roles";
import type { Role } from "@/requests/roles/types";
import type { User, UserStatus } from "@/requests/users/types";

export default function UserDetail(){
  const {userId=""}=useParams();const {t}=useTranslation("ui");const navigate=useNavigate();const location=useLocation();const {user:actor}=useAuth();const [user,setUser]=useState<User|null>(null);const [roles,setRoles]=useState<Role[]>([]);const [name,setName]=useState("");const [email,setEmail]=useState("");const [status,setStatus]=useState<UserStatus>("active");const [locale,setLocale]=useState("");const [timezone,setTimezone]=useState("");const [password,setPassword]=useState("");const [confirmPassword,setConfirmPassword]=useState("");const [currentPassword,setCurrentPassword]=useState("");const [mustChange,setMustChange]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState(false);
  const canManage=actor?.is_protected===true||actor?.roles.some((role)=>role.grants_all_permissions||role.permissions.some((permission)=>permission.permission_key==="users.manage"))===true;
  const isSelf=actor?.id===userId;
  const isPersonal=location.pathname.includes("/settings/profile/");
  const canEdit=canManage||isSelf;
  const canAssignRoles=actor?.is_protected===true||actor?.roles.some((role)=>role.grants_all_permissions||role.permissions.some((permission)=>permission.permission_key==="roles.assign"))===true;
  const statusOptions=(user?.is_protected?["active"]:["pending","active","disabled","locked"]) as UserStatus[];
  useEffect(()=>{Promise.all([getUser(userId),listRoles()]).then(([result,allRoles])=>{setUser(result);setRoles(allRoles);setName(result.display_name);setEmail(result.email);setStatus(result.status);setLocale(result.locale||"");setTimezone(result.timezone||"");setMustChange(result.must_change_password)}).catch(()=>setError(true))},[userId]);
  async function save(event:FormEvent){event.preventDefault();if(!name.trim()||!email.trim()||(isSelf&&!currentPassword)||(password&&password!==confirmPassword))return;setSaving(true);setError(false);try{const updated=await updateUser(userId,{display_name:name,email,locale,timezone,...(isSelf?{current_password:currentPassword}:{}),...(canManage&&!isSelf?{status,must_change_password:mustChange}:{}),...(password?{password}:{})});setUser(updated);setPassword("");setConfirmPassword("");setCurrentPassword("")}catch{setError(true)}finally{setSaving(false)}}
  async function remove(){if(!user||user.is_protected||!window.confirm(t("global.k_Settings_Users_DeleteConfirm")))return;setSaving(true);try{await deleteUser(user.id);navigate("/settings/access-control/users")}catch{setError(true);setSaving(false)}}
  async function toggleRole(role:Role,assign:boolean){if(!user)return;setSaving(true);setError(false);try{await setRoleUser(role.id,user.id,assign);const refreshed=await getUser(user.id);setUser(refreshed)}catch{setError(true)}finally{setSaving(false)}}
  if(!user)return <NexText color={error?"danger":"muted"}>{error?t("global.k_Settings_Users_Error"):t("global.k_Common_Loading")}</NexText>;
  return <section className="users-page">{canManage&&!isPersonal?<Link to="/settings/access-control/users">{t("global.k_Settings_Users_Back")}</Link>:null}<header><NexText variant="heading">{user.display_name}</NexText><NexText color="muted">{user.id}</NexText></header>{error?<NexText color="danger">{t("global.k_Settings_Users_Error")}</NexText>:null}
    {canEdit?<form className="user-form" onSubmit={(event)=>void save(event)}><NexText variant="subheading">{isSelf?t("global.k_Settings_Users_MyProfile"):t("global.k_Settings_Users_EditTitle")}</NexText><div className="user-form__fields"><NexInput id="user-name" label={t("global.k_Settings_Users_Name")} value={name} required onChange={(event)=>setName(event.target.value)}/><NexInput id="user-email" type="email" label={t("global.k_Settings_Users_Email")} value={email} required onChange={(event)=>setEmail(event.target.value)}/>{canManage&&!isSelf?<div><NexText as="span" variant="label">{t("global.k_Settings_Users_Status")}</NexText><NexSelect ariaLabel={t("global.k_Settings_Users_Status")} value={status} options={statusOptions.map((value)=>({value,label:value}))} onChange={setStatus}/></div>:null}<NexInput id="user-locale" label={t("global.k_Settings_Users_Locale")} value={locale} onChange={(event)=>setLocale(event.target.value)}/><NexInput id="user-timezone" label={t("global.k_Settings_Users_Timezone")} value={timezone} onChange={(event)=>setTimezone(event.target.value)}/><NexInput id="user-password" type="password" minLength={12} label={t("global.k_Settings_Users_NewPassword")} value={password} onChange={(event)=>setPassword(event.target.value)}/><NexInput id="user-confirm-password" type="password" minLength={12} label={t("global.k_Settings_Users_ConfirmPassword")} value={confirmPassword} required={password.length>0} onChange={(event)=>setConfirmPassword(event.target.value)}/>{isSelf?<NexInput id="user-current-password" type="password" label={t("global.k_Settings_Users_CurrentPassword")} value={currentPassword} required onChange={(event)=>setCurrentPassword(event.target.value)}/>:null}</div>{password&&password!==confirmPassword?<NexText color="danger">{t("global.k_Settings_Users_PasswordMismatch")}</NexText>:null}{canManage&&!isSelf?<label><input type="checkbox" checked={mustChange} onChange={(event)=>setMustChange(event.target.checked)}/> {t("global.k_Settings_Users_MustChange")}</label>:null}<div className="user-actions"><NexButton type="submit" disabled={saving||!name.trim()||!email.trim()||(isSelf&&!currentPassword)||(password.length>0&&password.length<12)||(password!==confirmPassword)}>{t("global.k_Common_Save")}</NexButton>{canManage&&!isSelf&&!user.is_protected?<NexButton type="button" variant="danger" disabled={saving} onClick={()=>void remove()}>{t("global.k_Common_Delete")}</NexButton>:null}</div></form>:<NexText color="muted">{t("global.k_Settings_Users_ReadOnly")}</NexText>}
    {canManage&&!isPersonal?<section className="user-form"><NexText variant="subheading">{t("global.k_Settings_Users_RoleAssignments")}</NexText><NexText color="muted">{t("global.k_Settings_Users_RoleAssignmentsDescription")}</NexText>{roles.filter((role)=>!role.is_system).map((role)=>{const assigned=user.roles.some((item)=>item.id===role.id);return <label key={role.id}><input type="checkbox" checked={assigned} disabled={!canAssignRoles||saving||user.is_protected} onChange={(event)=>void toggleRole(role,event.target.checked)}/> {role.title}</label>})}{roles.filter((role)=>role.is_system&&user.roles.some((item)=>item.id===role.id)).map((role)=><NexText key={role.id}>{role.title} · {t("global.k_Settings_Users_ManagedBySystem")}</NexText>)}</section>:<section className="user-form"><NexText variant="subheading">{t("global.k_Settings_Users_Roles")}</NexText>{user.roles.length?user.roles.map((role)=><NexText key={role.id}>{role.title}</NexText>):<NexText color="muted">-</NexText>}</section>}
  </section>
}
