import { request } from "@/requests/core/client";
import type { CreateUserInput, UpdateUserInput, User } from "./types";

export type { CreateUserInput, UpdateUserInput, User } from "./types";

const mockUsers: User[] = [
  {
    id: "0",
    display_name: "Admin",
    email: "admin@nexgestion.test",
    status: "active",
    locale: "zh-TW",
    timezone: "Asia/Taipei",
    must_change_password: false,
    failed_login_count: 0,
    locked_until: null,
    last_login_at: "2026-07-14T01:20:00.000Z",
    password_changed_at: "2026-06-15T09:30:00.000Z",
    is_protected: true,
    created_at: "2025-01-08T02:10:00.000Z",
    updated_at: "2026-07-14T01:20:00.000Z",
    deleted_at: null,
    employee_profile: null,
    roles: [
      {
        id: "role-admin",
        title: "Admin",
        description: "Full system access reserved for user id 0",
        is_system: true,
        grants_all_permissions: true,
        permissions: [],
      },
    ],
    groups: [],
  },
  {
    id: "1",
    display_name: "Mina Lin",
    email: "mina.lin@nexgestion.test",
    status: "active",
    locale: "zh-TW",
    timezone: "Asia/Taipei",
    must_change_password: false,
    failed_login_count: 1,
    locked_until: null,
    last_login_at: "2026-07-13T08:45:00.000Z",
    password_changed_at: "2026-05-21T04:15:00.000Z",
    is_protected: false,
    created_at: "2025-02-03T03:00:00.000Z",
    updated_at: "2026-07-13T08:45:00.000Z",
    deleted_at: null,
    employee_profile: {
      id: "employee-profile-1",
      user_id: "1",
      employee_number: "NX-1002",
      legal_name: "Mina Lin",
      preferred_name: "Mina",
      work_email: "mina.lin@nexgestion.test",
      work_phone: "+886-2-5550-1002",
      job_title: "Operations Manager",
      employment_status: "active",
      hire_date: "2025-02-03",
      termination_date: null,
      manager_employee_id: null,
      created_at: "2025-02-03T03:00:00.000Z",
      updated_at: "2026-07-13T08:45:00.000Z",
    },
    roles: [
      {
        id: "role-manager",
        title: "Manager",
        description: "Team management access",
        is_system: true,
        grants_all_permissions: false,
        permissions: [],
      },
    ],
    groups: [
      {
        id: "group-operations",
        name: "Operations",
        type: "department",
        status: "active",
        title: "Manager",
        joined_at: "2025-02-03",
        left_at: null,
      },
    ],
  },
  {
    id: "2",
    display_name: "Jordan Wang",
    email: "jordan.wang@nexgestion.test",
    status: "pending",
    locale: "en-US",
    timezone: "Asia/Taipei",
    must_change_password: true,
    failed_login_count: 0,
    locked_until: null,
    last_login_at: null,
    password_changed_at: null,
    is_protected: false,
    created_at: "2026-07-01T06:30:00.000Z",
    updated_at: "2026-07-01T06:30:00.000Z",
    deleted_at: null,
    employee_profile: {
      id: "employee-profile-2",
      user_id: "2",
      employee_number: "NX-1003",
      legal_name: "Jordan Wang",
      preferred_name: "Jordan",
      work_email: "jordan.wang@nexgestion.test",
      work_phone: "+886-2-5550-1003",
      job_title: "HR Specialist",
      employment_status: "onboarding",
      hire_date: "2026-07-01",
      termination_date: null,
      manager_employee_id: "employee-profile-1",
      created_at: "2026-07-01T06:30:00.000Z",
      updated_at: "2026-07-01T06:30:00.000Z",
    },
    roles: [
      {
        id: "role-hr",
        title: "HR",
        description: "People operations access",
        is_system: false,
        grants_all_permissions: false,
        permissions: [],
      },
    ],
    groups: [
      {
        id: "group-people",
        name: "People",
        type: "department",
        status: "active",
        title: "Specialist",
        joined_at: "2026-07-01",
        left_at: null,
      },
    ],
  },
  {
    id: "3",
    display_name: "Sofia Huang",
    email: "sofia.huang@nexgestion.test",
    status: "active",
    locale: "zh-TW",
    timezone: "Asia/Taipei",
    must_change_password: false,
    failed_login_count: 0,
    locked_until: null,
    last_login_at: "2026-07-12T13:05:00.000Z",
    password_changed_at: "2026-03-11T10:00:00.000Z",
    is_protected: false,
    created_at: "2024-11-18T01:45:00.000Z",
    updated_at: "2026-07-12T13:05:00.000Z",
    deleted_at: null,
    employee_profile: {
      id: "employee-profile-3",
      user_id: "3",
      employee_number: "NX-1004",
      legal_name: "Sofia Huang",
      preferred_name: "Sofia",
      work_email: "sofia.huang@nexgestion.test",
      work_phone: "+886-2-5550-1004",
      job_title: "Finance Analyst",
      employment_status: "active",
      hire_date: "2024-11-18",
      termination_date: null,
      manager_employee_id: "employee-profile-1",
      created_at: "2024-11-18T01:45:00.000Z",
      updated_at: "2026-07-12T13:05:00.000Z",
    },
    roles: [
      {
        id: "role-finance",
        title: "Finance",
        description: "Finance workspace access",
        is_system: false,
        grants_all_permissions: false,
        permissions: [],
      },
    ],
    groups: [
      {
        id: "group-finance",
        name: "Finance",
        type: "department",
        status: "active",
        title: "Analyst",
        joined_at: "2024-11-18",
        left_at: null,
      },
    ],
  },
  {
    id: "4",
    display_name: "Ethan Wu",
    email: "ethan.wu@nexgestion.test",
    status: "locked",
    locale: "en-US",
    timezone: "Asia/Taipei",
    must_change_password: false,
    failed_login_count: 5,
    locked_until: "2026-07-15T00:00:00.000Z",
    last_login_at: "2026-07-10T05:25:00.000Z",
    password_changed_at: "2026-02-18T07:40:00.000Z",
    is_protected: false,
    created_at: "2025-04-22T04:20:00.000Z",
    updated_at: "2026-07-14T00:10:00.000Z",
    deleted_at: null,
    employee_profile: {
      id: "employee-profile-4",
      user_id: "4",
      employee_number: "NX-1005",
      legal_name: "Ethan Wu",
      preferred_name: "Ethan",
      work_email: "ethan.wu@nexgestion.test",
      work_phone: "+886-2-5550-1005",
      job_title: "Support Engineer",
      employment_status: "active",
      hire_date: "2025-04-22",
      termination_date: null,
      manager_employee_id: "employee-profile-1",
      created_at: "2025-04-22T04:20:00.000Z",
      updated_at: "2026-07-14T00:10:00.000Z",
    },
    roles: [
      {
        id: "role-support",
        title: "Support",
        description: "Customer support access",
        is_system: false,
        grants_all_permissions: false,
        permissions: [],
      },
    ],
    groups: [
      {
        id: "group-support",
        name: "Support",
        type: "department",
        status: "active",
        title: "Engineer",
        joined_at: "2025-04-22",
        left_at: null,
      },
    ],
  },
  {
    id: "5",
    display_name: "Nora Tsai",
    email: "nora.tsai@nexgestion.test",
    status: "disabled",
    locale: "zh-TW",
    timezone: "Asia/Taipei",
    must_change_password: false,
    failed_login_count: 0,
    locked_until: null,
    last_login_at: "2026-05-19T09:15:00.000Z",
    password_changed_at: "2026-01-12T03:30:00.000Z",
    is_protected: false,
    created_at: "2024-08-09T05:10:00.000Z",
    updated_at: "2026-06-30T02:00:00.000Z",
    deleted_at: null,
    employee_profile: {
      id: "employee-profile-5",
      user_id: "5",
      employee_number: "NX-1006",
      legal_name: "Nora Tsai",
      preferred_name: "Nora",
      work_email: "nora.tsai@nexgestion.test",
      work_phone: "+886-2-5550-1006",
      job_title: "Sales Lead",
      employment_status: "inactive",
      hire_date: "2024-08-09",
      termination_date: null,
      manager_employee_id: "employee-profile-1",
      created_at: "2024-08-09T05:10:00.000Z",
      updated_at: "2026-06-30T02:00:00.000Z",
    },
    roles: [
      {
        id: "role-sales",
        title: "Sales",
        description: "Sales workspace access",
        is_system: false,
        grants_all_permissions: false,
        permissions: [],
      },
    ],
    groups: [
      {
        id: "group-sales",
        name: "Sales",
        type: "department",
        status: "inactive",
        title: "Lead",
        joined_at: "2024-08-09",
        left_at: "2026-06-30",
      },
    ],
  },
  {
    id: "6",
    display_name: "Kai Liu",
    email: "kai.liu@nexgestion.test",
    status: "active",
    locale: "ja-JP",
    timezone: "Asia/Tokyo",
    must_change_password: false,
    failed_login_count: 0,
    locked_until: null,
    last_login_at: "2026-07-14T02:00:00.000Z",
    password_changed_at: "2026-04-07T02:45:00.000Z",
    is_protected: false,
    created_at: "2025-09-01T00:30:00.000Z",
    updated_at: "2026-07-14T02:00:00.000Z",
    deleted_at: null,
    employee_profile: {
      id: "employee-profile-6",
      user_id: "6",
      employee_number: "NX-1007",
      legal_name: "Kai Liu",
      preferred_name: "Kai",
      work_email: "kai.liu@nexgestion.test",
      work_phone: "+81-3-5550-1007",
      job_title: "Product Designer",
      employment_status: "active",
      hire_date: "2025-09-01",
      termination_date: null,
      manager_employee_id: "employee-profile-1",
      created_at: "2025-09-01T00:30:00.000Z",
      updated_at: "2026-07-14T02:00:00.000Z",
    },
    roles: [
      {
        id: "role-product",
        title: "Product",
        description: "Product planning access",
        is_system: false,
        grants_all_permissions: false,
        permissions: [],
      },
    ],
    groups: [
      {
        id: "group-product",
        name: "Product",
        type: "department",
        status: "active",
        title: "Designer",
        joined_at: "2025-09-01",
        left_at: null,
      },
    ],
  },
  {
    id: "7",
    display_name: "Ivy Hsu",
    email: "ivy.hsu@nexgestion.test",
    status: "active",
    locale: "zh-TW",
    timezone: "Asia/Taipei",
    must_change_password: false,
    failed_login_count: 2,
    locked_until: null,
    last_login_at: "2026-07-11T11:35:00.000Z",
    password_changed_at: "2026-05-02T06:10:00.000Z",
    is_protected: false,
    created_at: "2025-06-16T02:00:00.000Z",
    updated_at: "2026-07-11T11:35:00.000Z",
    deleted_at: null,
    employee_profile: {
      id: "employee-profile-7",
      user_id: "7",
      employee_number: "NX-1008",
      legal_name: "Ivy Hsu",
      preferred_name: "Ivy",
      work_email: "ivy.hsu@nexgestion.test",
      work_phone: "+886-2-5550-1008",
      job_title: "QA Engineer",
      employment_status: "active",
      hire_date: "2025-06-16",
      termination_date: null,
      manager_employee_id: "employee-profile-1",
      created_at: "2025-06-16T02:00:00.000Z",
      updated_at: "2026-07-11T11:35:00.000Z",
    },
    roles: [
      {
        id: "role-engineering",
        title: "Engineering",
        description: "Engineering workspace access",
        is_system: false,
        grants_all_permissions: false,
        permissions: [],
      },
    ],
    groups: [
      {
        id: "group-engineering",
        name: "Engineering",
        type: "department",
        status: "active",
        title: "QA Engineer",
        joined_at: "2025-06-16",
        left_at: null,
      },
    ],
  },
  {
    id: "8",
    display_name: "Ryan Chang",
    email: "ryan.chang@nexgestion.test",
    status: "pending",
    locale: null,
    timezone: null,
    must_change_password: true,
    failed_login_count: 0,
    locked_until: null,
    last_login_at: null,
    password_changed_at: null,
    is_protected: false,
    created_at: "2026-07-08T07:05:00.000Z",
    updated_at: "2026-07-08T07:05:00.000Z",
    deleted_at: null,
    employee_profile: null,
    roles: [],
    groups: [],
  },
  {
    id: "9",
    display_name: "Grace Yeh",
    email: "grace.yeh@nexgestion.test",
    status: "active",
    locale: "en-US",
    timezone: "America/Los_Angeles",
    must_change_password: false,
    failed_login_count: 0,
    locked_until: null,
    last_login_at: "2026-07-09T16:50:00.000Z",
    password_changed_at: "2026-04-28T15:30:00.000Z",
    is_protected: false,
    created_at: "2024-12-02T08:25:00.000Z",
    updated_at: "2026-07-09T16:50:00.000Z",
    deleted_at: null,
    employee_profile: {
      id: "employee-profile-9",
      user_id: "9",
      employee_number: "NX-1010",
      legal_name: "Grace Yeh",
      preferred_name: "Grace",
      work_email: "grace.yeh@nexgestion.test",
      work_phone: "+1-415-555-1010",
      job_title: "Customer Success Manager",
      employment_status: "active",
      hire_date: "2024-12-02",
      termination_date: null,
      manager_employee_id: "employee-profile-1",
      created_at: "2024-12-02T08:25:00.000Z",
      updated_at: "2026-07-09T16:50:00.000Z",
    },
    roles: [
      {
        id: "role-customer-success",
        title: "Customer Success",
        description: "Customer success workspace access",
        is_system: false,
        grants_all_permissions: false,
        permissions: [],
      },
    ],
    groups: [
      {
        id: "group-customer-success",
        name: "Customer Success",
        type: "department",
        status: "active",
        title: "Manager",
        joined_at: "2024-12-02",
        left_at: null,
      },
    ],
  },
];

export async function listUsers() {
  if (import.meta.env.DEV) {
    return mockUsers;
  }

  const response = await request<{ users: User[] }>("/api/users");
  return response.users;
}

export function getUser(id: string) {
  if (import.meta.env.DEV) {
    const user =
      mockUsers.find((mockUser) => mockUser.id === id) ??
      mockUsers[Number(id)];

    if (!user) {
      throw new Error(`Mock user ${id} was not found`);
    }

    return Promise.resolve(user);
  }

  return request<User>(`/api/users/${encodeURIComponent(id)}`);
}

export function createUser(input: CreateUserInput) {
  return request<User>("/api/users", {
    method: "POST",
    body: JSON.stringify(input),
  });
}

export function updateUser(id: string, input: UpdateUserInput) {
  return request<User>(`/api/users/${encodeURIComponent(id)}`, {
    method: "PATCH",
    body: JSON.stringify(input),
  });
}

export function replaceUser(id: string, input: UpdateUserInput) {
  return request<User>(`/api/users/${encodeURIComponent(id)}`, {
    method: "PUT",
    body: JSON.stringify(input),
  });
}

export function deleteUser(id: string) {
  return request<void>(`/api/users/${encodeURIComponent(id)}`, {
    method: "DELETE",
  });
}
